sudo: false

language: python

python:
  - "2.7_with_system_site_packages"

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27

install:
  - "pip install tox"
  - "npm install -g gulp"
  - "npm install"
  - "gulp install"
  - "gulp dist"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"
